### ISSUE TITLE
Fields missing in some objects not accounted for

### ISSUE THREAD

**Issue by prabhat112** [rars/ng2csv#5]
I have a JSON object in this way where some fields are not mandatory in the JSON as shown below.
[ {   id: 1, name: 'Alice', City:Madison, Phno:9191234567  },
        {   id: 2, name: 'Bob' ,City:New York },
       {   id: 2, name: 'Bob',City:Miami,Phno:9191234567  },
       {   id: 2, name: 'Bob' ,City:Atlanta,Phno:9191234567  }  ]
It gave me a toString() undefined error. Since there was no Phno field in the 2nd object, the field value was being taken as undefined and undefined.toString() was giving me the error in runtime. 
I added a line to the _loop_1 function in the AutoCsvRowMapper.js file definition by keeping an if else condition. That fixed everything. 
Let me know if you would be open to incorporating this fix.

**Comment by rars** [comment]
Thanks for raising this issue. I've made a quick fix and released 0.1.2 to address this, but I foresee a problem with the AutoCsvRowMapper if the first row in the data does not contain all the property names you want serialised. I'm open to improving this, but the change should be in the source `.ts` Typescript file, not the `.js` files that are the result of compiling the source. I may look at this over the coming week if I have time.

Please let me know if the 0.1.2 release helps with your issue or if you still have problems with it.

**Comment by prabhat112** [comment]
Like you said, the first row in the data will be determining the columns present. But for now 0.1.2 release has fixed my Issue. Thanks.

**Comment by rars** [comment]
I've released and pushed 0.2.0 that should determine the columns present by examining all objects in the data to be serialised. I'll close this issue now, but let me know if you have any problems.
